[package]
name = "graphql"
version = "0.1.0"
authors = ["Markus Ast <m@rkusa.st>"]

[dependencies]
serde = "0.9"
serde_derive = "0.9"
serde_json = "0.9"
futures = "0.1"
tokio-service = "0.1"
hyper = { git = "https://github.com/hyperium/hyper.git", branch = "master" }
ctx = { path = "../ctx" }

